version: "3"
services:
  database:
    image: postgres:14
    volumes:
      - ./database:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - .env
